### ISSUE TITLE
recommend contributions to `rebase upstream/dev` prior to PR

### ISSUE THREAD

**Issue by eldad-a** [BuildACell/BioCRNPyler#105]
For future PRs and contibutions, it may be worth including in [how-to-sync-your-BioCRNPyler-fork](https://github.com/BuildACell/BioCRNPyler/wiki/how-to-sync-your-BioCRNPyler-fork)

```
git fetch upstream dev
git checkout <branch_with_amazing_new_feature>
git rebase upstream/dev
git push origin <branch_with_amazing_new_feature>
```

NB `git fetch upstream dev` without `/`, while `git rebase upstream/dev` with.

This is motivated by comments in #100 .

**Comment by ayush9pandey** [comment]
I have been reading up on the recent rebase issues on the PRs from @dr3y and @eldad-a, glad all that got fixed but it got me wondering why these problems occurred in the first place? Like my usual workflow is much simpler (atleast to me) and it works (I think). 


* git checkout -b my_new_branch

<work on this branch, change files whatever..>

* git add .
* git commit -m "new commits"
* git pull upstream dev

Fix  merge conflicts if any

* git push origin my_new_branch

Go to github and create a pull request from my_new_branch to upstream/dev.

I understand that `fetch` instead of directly `pull` is a better practice but is that the only reason?

**Comment by eldad-a** [comment]
Disclaimer: I'm not a git savvy...

Guess it boils down to how you'd like your *history* (`log`) to look like.

According to [git-when-to-merge-vs-when-to-rebase](https://www.derekgourlay.com/blog/git-when-to-merge-vs-when-to-rebase/), it may be that a good practice in this case would be:
```
git fetch upstream dev
git rebase −p upstream/dev
```
`-p` shortcut for `−−preserve−merges`.

I found the following also very helpful:
[scikit-image: Development workflow](https://scikit-image.org/docs/dev/gitwash/development_workflow.html)
and
[How to contribute to scikit-image](https://scikit-image.org/docs/stable/contribute.html)

**Comment by zoltuz** [comment]
First of all, there was no problem in any of the mentioned PRs. I just wanted to test how easily people can pick up rebasing on their own branches. As it was mentioned in the previous message, rebase is useful to make a cleaner commit log. 
For example, here's a section of the log for this repo:
<img width="972" alt="Screenshot 2020-06-24 at 18 57 51" src="https://user-images.githubusercontent.com/17138838/85608048-9ca43b80-b64c-11ea-9244-4936f4a4111d.png">
Because of the merge commits there are multiple paths running around and merging into each other (merge commit). It the long run, it will be hard to see what was going on. (Especially if you are new to the project)

Rebase is an advanced feature of git, I wouldn't make it compulsory for contribution to the code. However, it is part of a much wider discussion, namely what put into our CONTRIBUTING.md.

**Comment by zoltuz** [comment]
Hi @eldad-a, 
Thanks for the suggestion, we decided to [squash commits in a PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits), which gives us the same outcome without advance git commands.
