### ISSUE TITLE
discussion for a CONTRIBUTING.md 

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#107]
Hi all, 

I think it is time to codify our workflow on this repo. Now that we have the new branch structure in place, it would be great to put together a contributing instruction manual for everyone who wants to contribute to the code. 

here are some examples:

https://github.com/Opentrons/opentrons/blob/edge/CONTRIBUTING.md
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
https://github.com/atom/atom/blob/master/CONTRIBUTING.md
https://mozillascience.github.io/working-open-workshop/contributing/

For some reason, I couldn't assign Andrey to this issue page. Sorry! @dr3y you are more than welcome to contribute as well!

**Comment by WilliamIX** [comment]
I am looking into this and have also read some of the other threads around merging versus rebasing etc. A lot of this is new to me, and the number of features, possibilities, and complications is a little overwhelming. As a starting point, I think we should aim to making contributing to the software package as easy as possible. Here is a tentative workflow and I wonder what you all think:

1. Developer creates local MyDev branch for development work (based off of origin dev branch)
2. After completing work, Developer merges or rebases origin dev branch into MyDev and makes sure their code is up to date with the most recent dev branch. _I think we should be agnostic here about rebase vs merge, because merging is more natural to many new developers we don't want to ban it, but rebasing might be used by more git-savvy devs._
3. MyDev branch must pass all tests via python setup.py test locally. _The percentage of code tested by coverage does not need to increase, although making tests and examples is strongly encouraged._
4. Developer makes a PR for MyDev Branch to be merged into origin dev branch.
5. This PR must pass all tests via Travis [likely changes will be library dependencies etc needed to be put in try catch statements]
6. **CASE 1:** MyDev branch is a relatively small set of features (like new Components, Mechanism etc) and is merged with Squash and Merge. **CASE 2:** MyDev branch makes very extensive "global" changes to the code. In this case, we (the PR moderators) will require a rebase in order to clean up the git commit history.
7. Periodically the dev branch is merged into the master branch. This will always result in a new version number. This will require that the percent of code tested via coverage increases with every merge. Developers who push to the dev branch but never follow up with tests (I'm thinking of myself) should be publicly shamed.

**Comment by zoltuz** [comment]
Don't worry, many things are new to me as well. I also agree we should keep the barrier to contribute very low. Having said that we should also aim to incorporate many open-source 'industrial' standards (in a pace we are comfortable with). These standards, on one hand, ensure that the project welcomes people to contribute. On the other hand, BioCRNPlyer continues to have maintainable code (high code coverage, good unit tests, good examples, good git history--who did what when why)

@ayush9pandey  Any comment, suggestion?

**Comment by ayush9pandey** [comment]
Yes. We should definitely add a contributing.md file. Is there a draft already in some branch? 

I think we had a discussion on the basic contribution guidelines that we want - docstrings for classes, functions, jupyter notebook example(s) if new major feature is added, pull request from a branch/fork to the dev branch with all Travis unit tests passing...these are just the minimal guidelines that we should have, maybe I missed a couple.

**Comment by ayush9pandey** [comment]
This has been fixed. There is a contributing.md in docs/ now.
