### ISSUE TITLE
merge two promoter initialization cases 

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#150]
![Screenshot 2020-08-01 at 18 58 44](https://user-images.githubusercontent.com/17138838/89107444-0cb29800-d429-11ea-8379-3bbcffe6a696.png)

**Comment by WilliamIX** [comment]
@zoltuz thoughts on the above? is this a bug or is there a better way to do this?

**Comment by zoltuz** [comment]
I don't think there's a bug, but this construction seems a bit odd to me. Is there a reason why a copy of an existing promoter is needed?
This looks a bit more future proof:
```python
# in dna_assembly.py
if isinstance(promoter, str):
    self.promoter = Promoter(assembly=self, name=promoter,
                             transcript=self.transcript,
                             protein=protein)
elif isinstance(promoter, Promoter):
    self.promoter = Promoter.from_promoter(promoter)

# dna_part_promoter.py
class Promoter(DNA_part):
   @classmethod
   def from_pomoter(cls, promoter):
            return  cls(name=promoter.name, assembly = self, transcript = promoter.transcript, protein = promoter.protein)
```
in this case, if promoter ever changes, we don't need to edit ```DNAAssembly```

**Comment by WilliamIX** [comment]
The copying is very intentional. All Components are copied when they are added to a Mixture and SubComponents like Promoters are copied when they are added to a DNAassembly or DNAconstruct. Awhile back we had a long discussion on this - the idea is that the same Promoter could be used in multiple DNAassemblies this way without issue and that the same DNAassembly could be used in multiple Mixtures.

We are using copy.deepcopy(obj) everywhere for all the copying. I do not think we need to make our own copy methods as you are suggesting. In particular, a classmethod from_promoter might have to be rewritten for every single subclass of Promoter which will create a lot of maintenance in the long run. 

However, I am tacitly assuming pythons copy function works - if there are known issues with it that you have encountered, we should definitely discuss this because this could have ramifications in many many places in the code.

**Comment by WilliamIX** [comment]
promoter (and RBS) have a .update_component function that encapsulates what is going on here. Thanks @dr3y for pointing this out.

Here is a suggestion:
`.update_component(transcript = None, protein = None, assembly = None....)` - for this particular places, use the assembly= keyword to push all the logic into the Promoter class.

**Comment by dr3y** [comment]
another thing to fix here is perhaps to unify terminology between `update_component` and `DNA_assembly`. Because when I made update component there are some reasons why I didn't use the words "protein" "transcript" "assembly" etc. But the reasons were, that I needed the ability to have multiple transcripts and multiple proteins and things related to that

**Comment by zoltuz** [comment]
#215 sovled it
