### ISSUE TITLE
Port over some existing parameters from Vipul's work

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#31]
Needs to be in the correct new format (what is that format?)
Test the parameter loading and all the levels --> unit tests!

**Comment by ayush9pandey** [comment]
In my opinion, to make bioCRNpyler more useful and reachable to wider audience, this issue is important. There is plenty of parameter data and "parts" library information that is available in MATLAB txtlsim that we ought to move to bioCRNpyler. 

Now that the parameter loading and unit tests are more or less working, it might be a good time to act on this. What would be the best way to port over information from that toolbox? It would definitely be helpful if we could directly read the config files available in txtlsim. What other things need to be done?

**Comment by WilliamIX** [comment]
This goes hand-in-hand with sigma factors, energy models, and linear/vs plasmid DNA

**Comment by zoltuz** [comment]
#210 took care of this
