### ISSUE TITLE
Create Design Specs for SBOL Interface.

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#72]
What does an SBOL interface look like? 
* Load an SBOL file that compiles into a set of components

What should the functionality be? 
* Ability to simulate SBOL objects with different mechanisms and in different contexts (Mixtures)

What new features do we need?
* SBOL Loading
* Smarter construction of more general assembles (multiple RBS's, Promoter orientation, terminators, etc).

**Comment by dr3y** [comment]
I propose SBOL -> `DNA_part`'s -> `DNA_construct`

Can you define new parts with SBOL? importing new `DNA_part` definitions using some kind of input file would be interesting.

Has anyone ever seen an "SBOL file"? I was not aware that SBOL was anything besides a set of SVG graphics

**Comment by dr3y** [comment]
here is an example of an SBOL file:
https://synbiohub.org/public/igem/BBa_K1157018/1
click on "download SBOL file"

**Comment by dr3y** [comment]
Two problems with SBOL in its current state:

1. I don't know how to say a part is reverse, in SBOL. If you look at SynBioHub none of the parts there are in the reverse orientation, and people even define things like proteins or promoters where the sequence is actually reverse, so that the sequence of the construct ends up being correct, but the definition of the parts is all forwards. 

2. `pysbol2` does NOT have a built in good way to identify the types of parts, since the native SBOL method is to have a Sequence Ontology URL. Resolving a Sequence Ontology and saying things like "A _Plasmid_Vector_ is a type of _Plasmid_" is impossible, as far as I know, and we would probably have to implement our own interface with sequenceontology.org (highly undesireable, in my opinion)

**Comment by WilliamIX** [comment]
These are very good points. I am increasingly thinking that an SBOL interface maybe is not the priority I thought it was. In particular, the timing of our project and the new version of SBOL couldn't coincide worse. I think focusing on the other elements of BioCRNpyler and add SBOL sometime in the future (after pySBOL3 is released) makes more sense.

**Comment by zoltuz** [comment]
I tend to agree with you. I was excited first because of the apparent connection between SBOL and BioCRNpyler, but the more we dig into this more hoops we discover that we need to jump through. At the same time, the only benefit I see is the ability to "beam down" DNA parts from a synbiohub server, which we then combine with different Mixtures and Mechanisms. (As far as I can see this is going to be a one-way street unless we exploit some new features of SBOL3 and store extra information in a new SBOL file that we send back to synbiohub). Given the current trend, we will have fewer gene circuits, but more models (i.e. 3 Mixtures x 2 TL Mechanisms, etc), which suggest to me we can manage the number of DNA parts/gene circuits that we manually define. 

Probably focusing our effort on a more coherent, more feature-complete software that has well-defined interfaces, which can be later used for an SBOL interface, is a better use of our time.

**Comment by dr3y** [comment]
Here is what I have learned so far, for posterity and for whenever we get back to this:

1) I am wrong, features can have a direction. The way to get it is as follows:
```
hub = sbol2.PartShop("https://synbiohub.org")
doc = sbol2.Document()
hub.pull(,'https://synbiohub.org/public/iGEM_2016_interlab/Medium_2016Interlab/1',doc)
cd = doc.getComponentDefinition('https://synbiohub.org/public/iGEM_2016_interlab/Medium_2016Interlab/1')
cd.sequenceAnnotations[3].component
> 'https://synbiohub.org/public/iGEM_2016_interlab/Medium_2016Interlab/RBS_Component/1'
cd.sequenceAnnotations[3].locations[0].orientation
> 'http://sbols.org/v2#inline'
```
I guess the idea is that the `orientation` member could be "inline" or "reverseComplement". Unanswered questions (but ones we might be able to answer, given some playing around) here are the following:
- given a `Document`, how to automatically identify the component which defines the plasmid or construct that should be analyzed? Or should the user specify that, since `Document`s can contain many such components?
- given a `ComponentDefinition` which has `sequenceAnnotations` (not all of them might have those? unclear) how do we get them in the right order? Here we are getting `sequenceAnnotations[3]` to get the RBS, but the RBS should be the second component, or the third, if the first component is the plasmid (as it is in this document), however the index is [3] which is the fourth component. Maybe `sequenceAnnotations` aren't in order, but then you have to cross reference the order with `primarySequence` or something? Unclear.
- how do we know that an RBS is an RBS? This connects with point 2, below
- how to resolve parts that are made of other parts?

2) Jake Beal had this to say about using Sequence Ontology to figure out that a plasmid_vector is the same as a plasmid (or similar questions pertaining to annotations):
>>This isn't exactly a pySBOL issue, but more a general question of how to work with ontologies in python. There are a lot of different ways to go about this, and you might find some of the tutorials and resources on OBOFoundry useful. Of the various approaches, it seems like the https://pypi.org/project/Owlready2/ library is one of the preferred routes, if you're OK with holding the ontology locally, while SPARQL with Ontobee (http://www.ontobee.org/) seems better if you want to use them via a live online source.

**Comment by WilliamIX** [comment]
Just an update: I am talking to Tom Mitchel, who is writing pySBOL3, the software might be farther along than we thought. Will keep my findings posted in this thread.

**Comment by WilliamIX** [comment]
Notes from my meeting with Tom:

-  State of pySBOL3: just starting, but he's making rapid progress. Core class structure will be done by October most likely (demoing at Combine). Validators and higher level functionality will take longer. He would love help with higher level functionality - for example wrapper functions that allow biologists to easily create the kinds of SBOL files they are interested in or display SBOL files in ways that are meaningful. The best way to see what exists in the package so far (and how to use it) is via the unit tests.
-  General notes on thinking about SBOL: 
   -  every Component/SubComponent/Feature can be fully defined in the SBOL file or defined as a reference URL to some other place.
   -  There is no "right" way to make an SBOL file. For example, a sequence consisting of a Promoter, RBS, and CDS might be specified by a series of Locations of SubComponents or by a series of Constraints between the Components using ontology terms like "Precedes" to specify order.
   -  Most SBOL functional and relational information is encoded via different Ontologies. Many common examples are listed in the SBOL3 [specification](https://www.degruyter.com/view/journals/jib/17/2-3/article-20200017.xml), but these are not restrictive.
   -  SBOL files should be thought of as a "bag" of Components/Features/Interactions/etc which are connected to each other via other elements in the bag.
-  Examples of pySBOL can be found [here](https://github.com/SynBioDex/pySBOL3/tree/master/examples). Other examples of SBOL can be found in the [test suite](https://github.com/SynBioDex/SBOLTestSuite)
