### ISSUE TITLE
Biocrnpyler SBML issue when simulating with Bioscrape

### ISSUE THREAD

**Issue by AnkitaRoychoudhury** [BuildACell/BioCRNPyler#78]
When using **CRN.simulate_with_bioscrape_via_sbml(timepoints, initial_condition_dict = x0, file = 'CRN.sbml')** in biocrnpyler, the outputs are not the same as when simply modeled in bioscrape. However, when using **CRN.simulate_with_bioscrape(timepoints, initial_condition_dict = x0)**, the outputs are the same as bioscrape. This seems to point towards a bug? I have attached an .ipynb and .html file with more detailed notes about the simulations and the differences. 
[sbml_issue.zip](https://github.com/BuildACell/BioCRNPyler/files/4684109/sbml_issue.zip)

**Comment by WilliamIX** [comment]
@ayush9pandey can you take a look at this? I helped Ankita narrow in on the issue and I think it's an SBML issue because simulate_with_bioscrape(...) directly creates a bioscrape model without using SBML works - unclear if it is on the bioscrape loading or biocrnpyler saving side.

**Comment by ayush9pandey** [comment]
@AnkitaRoychoudhury  can you help debug this issue by digging into it a little bit. Here are a few things that you could try:
1. Write your CRN model as bioscrape model and write a bioscrape XML for it. Compare this XML file with the SBML XML file. 
2. Write your CRN model to an SBML XML file (check if the XML has everything that you expect), then load this SBML using bioscrape manually and run the simulations again.

It would be helpful if you could run some of these tests to pinpoint this issue. Once we know where the bug is it could be easily fixed. 

Also, a minor note : the standard way to write SBML models is to use .xml extension for the files (not .sbml).

**Comment by ayush9pandey** [comment]
Current issues with SBML loading/writing that I could find (there could be more) : 

1. BioCRNpyler SBML writing does not write stoichiometry of all reactants and products correctly (this was fixed for bioscrape, so it should be easy to fix here).

2. BioCRNpyler writes local parameter names to SBML with edited IDs but then due to the new annotation based loading of models in bioscrape, new DummyVar..... ids are created, as a result, parameter name conflicts arise. 

There could be more issues...will keep this issue updated.

**Comment by ayush9pandey** [comment]
I tracked the issue down - stoichiometry coefficients were not being written properly by bioCRNpyler to SBML file. Fixed in PR #83.

**Comment by ayush9pandey** [comment]
Travis check failed - Is that a problem with different versions of coverage @zoltuz  ?

**Comment by AnkitaRoychoudhury** [comment]
I just cloned the new version of biocrnpyler, did the python setup.py install, and reran the same notebook after clearing the kernel but I seem to be having the same issue @ayush9pandey 

I tried to simulate with XML and it seems that everything should be as expected in the file. I've attached it here just in case.
[CRN.xml.zip](https://github.com/BuildACell/BioCRNPyler/files/4714058/CRN.xml.zip)

**Comment by ayush9pandey** [comment]
Did you use the `sbml_fix` branch? It is not merged yet with the master so if you want to use the master branch you'll have to wait for a day or two..

**Comment by WilliamIX** [comment]
My bad - I thought you had merged this and asked Ankita to test it. Could you please notify the BE240 slack when the fix is out?

**Comment by zoltuz** [comment]
PR #83 checked and merged. I don't have slack access, but hopefully, this comment makes enough buzz. @AnkitaRoychoudhury please have a look and reopen the issue if the problem still persists.
