### ISSUE TITLE
New Parameter Specification

### ISSUE THREAD

**Issue by WilliamIX** [BuildACell/BioCRNPyler#80]
- Mixtures are Global Parameters [Each Mixture object has it's own set of parameters - right now this is not the case for some reason].

- Components can have Local Parameters which Supersede all Mixture Parameters.

How to do it Discussion:

1. Use objects instead of dictionaries. 
       Make a ParameterDatabase which stores many ParameterEntry objects.
2. Different Kinds of ParameterEntries? Please Discuss
3. Each Mixture has it's own ParameterDatabase and each Component can have it's own ParameterDictionary. 

Parameter Loading Hierarchy: 
![image](https://user-images.githubusercontent.com/332650/83295734-51f5e780-a1a4-11ea-9254-b8c4a89ca594.png)

@zoltuz  could you please give me feedback soon - hoping to get to this in the next couple of days.

**Comment by WilliamIX** [comment]
Here is an idea: when reactions get a parameter in their constructor, they actually get ParameterEntry [numerical rates will still be supported as well]. We can then use this to name parameters when we write SBML [and in SBML annotations] so that BioCRNpyler models can be easily accessed for parameter inference.

@DIEGOA363 this sounds a lot like what you and I were talking about - would this solve your parameter ID needs?

**Comment by WilliamIX** [comment]
Another useful feature to include with our new parameter update: 

We should have the loaded parameters in reactions know the "perfect" parameter key (mechanism_id, part_id, param_name) as well as their actual parameter key that was used via defaulting. Then there should be a way to print this out (probably in CRN.pretty_print(...)). This will help people create parameter files more easily and see which parameters are being loaded from where.

**Comment by DIEGOA363** [comment]
This sounds like a good plan to me. Your last idea about comparing "perfect" and the actual parameter key will very valuable for debugging. I was also thinking it might be useful to know what parameters a Mechanism is expecting, that way people using BioCRNPyler know how to format the the parameter file without having to dig through code. Similarly, you should be able to view all the parameters of a Mixture.

In summary, and correct me if I misunderstood something:

- parameters will be ParameterEntry objects instead of dictionaries
- mixtures will have a ParameterDatabase
- components can also have a ParameterDatabase, overriding the mixture 
- Component.get_parameter(..) returns a ParameterEntry
- Reaction constructor accepts both single values (old behavior) and ParameterEntry (new behavior)

As of right now I can't think of use cases for different ParameterEntries.

**Comment by WilliamIX** [comment]
ParameterEntries are how we store the keys showing where parameters come from - might also be helpful for comparing to the "perfect keys" we are looking for.

**Comment by zoltuz** [comment]
PR #124 added these features.
